import { Inter } from "next/font/google";
import "./globals.css"
import "react-toastify/dist/ReactToastify.css";
import { DataProvider } from "./Redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0"/>
      <body className={inter.className}>
        <DataProvider>
        {children}
        </DataProvider>
        </body>
    </html>
  );
}
